baseURL: https://www.jskherman.com/
languageCode: "en-us"
title: "Je Sian Keith Herman"
paginate: 5
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: JSK
  description: "Personal website for Je Sian Keith Herman where I share content based on my experiences as an ML Engineer & self-taught programmer."
  author: Je Sian Keith Herman
  images: ['avatar.png']

  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowShareButtons: true
  # disableSpecial1stPost: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  comments: true
  hidemeta: false
  showtoc: true
  tocopen: false
  # math: true
  # GoogleAnalyticsID: 
  CloudinaryUrl: "https://res.cloudinary.com/jskherman/image/upload"

  profileMode:
        enabled: false
        title: JSK
        imageUrl: "avatar.png"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: About
              url: about
            - name: Blog
              url: blog
            - name: Projects
              url: projects/
            # - name: Tags
            #   url: tags
            # - name: Search
            #   url: search
  
  assets:
    disableFingerprinting: true
    favicon: icons/favicon.ico
    favicon16x16: icons/favicon-16x16.png
    favicon32x32: icons/favicon-32x32.png
    apple_touch_icon: icons/apple-touch-icon.png
    android-chrome: icons/android-chrome-512x512.png
    disableHLJS: true

  label:
    text: JSK's Blog
    # icon: avatar.png
    # iconHeight: 35

  homeInfoParams:
    Title: "Hi there! \U0001F44B"
    Content: |
      - Welcome to my website! This is the right place to discover more about me if you're interested. I share my thoughts, opinions, projects showcases and experiences.
      -
      - And if you enjoy reading the content, consider sharing them with your friends, family, and acquiantances. Or if you believe I could improve something, leave a feedback through any of my contact details.
      
  socialIcons:
  - name: Twitter
    url: https://twitter.com/jskherman
  - name: Github
    url: https://github.com/jskherman
  - name: LinkedIn
    url: https://www.linkedin.com/in/jskherman/
  # - name: medium
  #   url: https://medium.com/@Jarmos
  # - name: instagram
  #   url: https://www.instagram.com/jarmos.san/
  # - name: facebook
  #   url: https://www.facebook.com/jarmos.san/
  # - name: email
  #   url: mailto:somraj.mle@gmail.com
  - name: KoFi
    url: https://ko-fi.com/jskherman
  # - name: BuyMeACoffee
  #   url: https://www.buymeacoffee.com/jsk_herman
  - name: "RSS"
    url: index.xml
    
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: false
    linkFullImages: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content"]
  
  # analytics:
  #       google:
  #           SiteVerificationTag: "XYZabc"

taxonomies:
    category: categories
    tag: tags

menu:
  main:
  - name: About
    identifier: about
    url: about/
    weight: 1
  - name: Now
    identifier: now
    url: now/       #https://jskherman.notion.site/Now-ec792577baf44dd3b441171240dabb92
    weight: 2
  - name: Blog
    identifier: blog
    url: blog/
    weight: 3
  # - identifier: projects
  #   name: Projects
  #   url: projects/
    weight: 4
  - name: Tags
    url: tags/
    weight: 9
  - name: Search
    url: search/
    weight: 10
  # - name: Services
  #   identifier: hiring
  #   name: Services
  #   url: services/
  #   weight: 4
  # - name: Collaborate
  #   identifier: collaborate
  #   url: collaborations/
  #   weight: 5
  # - name: Newsletter
  #   identifier: newsletter
  #   url: https://jarmos.ck.page/newsletter
  #   weight: 6

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
      # anchorLineNos: true
      # codeFences: true
      # guessSyntax: true
      # lineNos: true
      # noClasses: false
      # style: "borland"
      anchorLineNos: false
      codeFences: true
      guessSyntax: false
      lineNos: true
      lineNumbersInTable: false
      noClasses: true
      style: "monokai"

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

ignoreFiles:
  - \.qmd$
  - \.ipynb$